<a href="https://colab.research.google.com/github/mwithgod3952/BasicTensorFlow/blob/main/Tensorflow_summary_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

    TensorFlow has two main components that we will try to understand.
        * Graphs
        * Sessions
    TensorFlow works by building a graph of defined computations. It is simply a way of defining the operations.
    A TensorFlow session allows parts of the graph to be executed. It allocates memory and resources and handles the execution of the operations and computations we've defined.  
        If i were to create some variable that gets added to the graph, and maybe that variable is the sum or the summation of two other variables.
        what we need to understand is that it doesn't actually evaluate. it simply states that is the computation we've defined. 
        we just have that equation there. We know that this is the value, but we haven't evaluated it.  

    Swssion is essentially a way to execute part or entire graph. 
    So when we start in a session, what we do is we start executing different aspects of the graph.
    So we start at the lowest level of the graph where nothing is dependent on anything else, and we move our way through the graph, and start doing all of the different partial computations that we've defined.

In [1]:
from google.colab import drive; drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [2]:
import os
os.chdir('/content/drive/MyDrive/class_folder/Basic_Tensorflow')
if os.getcwd().split('/')[-1] == 'Basic_Tensorflow':
    wp = os.getcwd()
else:
    print('error is occured')

##### ***Importing TensorFlow***

    - The first steps here is going to be to select the correct version of TensorFlow

In [3]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


##### ***Tensors***

    A tensor is a generalization of vectors and matrices to potentially higher dimensions.
    Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes.

###### ***matrix generation***

In [4]:
# Here is a "scalar" tensor . A scalar contains a single value, and no axes
Rank0_Tensor = tf.constant(4)
print(Rank0_Tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [5]:
# A rank-1 tensor is like a list of values. A vector has one asxis/
Rank1_Tensor = tf.constant([2.0, 3.0, 4.0])
print(Rank1_Tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [6]:
# A matrix or rnak-2 tensor has two axes
# The shape of this matrix is 3, 2
Rank2_Tensor = tf.constant([[1, 2],
                            [3, 4],
                            [5, 6]], dtype=tf.float16)
print(Rank2_Tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [7]:
# The shape of this matrix is 3, 2, 5
data = [x for x in range(30)]
_data = [data[x:x+5] for x in list(range(0, 30, 5))]
Rank3_Tensor = tf.constant([[_data[0], _data[1]],
                            [_data[2], _data[3]],
                            [_data[4], _data[5]]])
Rank3_Tensor

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]], dtype=int32)>

###### ***matrix operations***

In [8]:
a = tf.constant([[1, 2],
                 [3, 4]], dtype=tf.int32)
b = tf.ones([2, 2], dtype=tf.int32)

print('\n')
print(tf.add(a, b))
print('\n')
print(tf.multiply(a, b))
print('\n')
print(tf.matmul(a, b))
print('\n')



tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)




In [9]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])
print('\t 1. Find the largest value: ', tf.reduce_max(c)) 
print('\t 2. Find the index of the largest value: ', tf.argmax(c))

	 1. Find the largest value:  tf.Tensor(10.0, shape=(), dtype=float32)
	 2. Find the index of the largest value:  tf.Tensor([1 0], shape=(2,), dtype=int64)


In [63]:
# library setting
import numpy as np

# Compute the softmax
'''
    - 기본적인 softmax 연산은 아래와 같이 tf 라이브러리를 통해 매우 쉽에 도출할 수 있다.
    - 더불어, softmax는 기본적으로 sigmoid의 결과값을 normalization한 것으로, 명확한 이해를 위해서는 sigmoid의 개념을 이해해야 하며, sigmoid를 적극적으로 활요하는 알고리즘 중 하나인
    Logistic Regression을 통해 해당 경과를 코드로 설명해보겠다.

        ** 변수설명 **

        1. cost : 기존의 linear regression의 cost 그래로를 sigmoid function을 적용하여 계산하면 시작점에 따라 local minimum 값이 달라지고 따라서 박복학습에 따라  
        global minimum 값에 수렴할 수 없게 됩니다. 이런 문제를 해결하기 위해, y = 0인 경우와 1인 경우에 대하여 log를 취한 2개의 cost function을 취하게 되고 이를 하나로 결합하기 위해
        (1 - y)을 추가한 것 들 값들의 평균을 구하게 됩니다.

        2. lr : learning rate 

        3. W : Weight

        4. b : bias

'''

# logistic regression with sigmoid function
'''
    cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis) + (1-Y)*tf.log(1-hypothesis)))
    lr = tf.Variable(0.1)
    optimizer = tf.train.GradientDescentOptimizer(a)
    train = optimizer.minimize(cost)
'''
# 이번에는 실제 Logistic regression을 만들어보겠습니다.

#   2. define dataset
x_train = np.array([[1., 1.],
                    [1., 2.],
                    [2., 1.],
                    [3., 2.],
                    [3., 3.],
                    [2., 3.]], dtype=np.float32)
y_train = np.array([[0.],
                    [0.],
                    [0.],
                    [1.],
                    [1.],
                    [1.]], dtype=np.float32)

x_test = np.array([[3., 0.],
                   [4., 1.]], dtype=np.float32)
y_test = np.array([[0.],
                   [1.]], dtype=np.float32)


#   2. Initializing Weight
tf.random.set_seed(1)
W = tf.Variable(tf.random.normal([2, 1], mean=0.0))
b = tf.Variable(tf.random.normal([1], mean=0.0))

#   3. Train the model
learning_rate = 0.01

def predict(X):
    z = tf.matmul(X, W) + b
    hypothesis = 1 / (1 + tf.exp(-z))
    return hypothesis

print('\n')
for i in range(2*10**3+1):
    '''
        GradientTape는 지정한 모델의 예측력에 대한 미분값을 저장합니다.
        일반적으로는 Optimizer와 함께 사용할테지만, 이번 예제는 cost값을 직접 계산해볼 것임으로 cost값과 및 weight, bias간의 각 미분값을 구하여 학습에 따른 변화 양상을 살펴보겠습니다.
    '''
    with tf.GradientTape() as tape:
        hypothesis = predict(x_train)
        cost = tf.reduce_mean(-tf.reduce_sum(y_train*tf.math.log(hypothesis) + (1 - y_train)*tf.math.log(1 - hypothesis)))
        W_grad, b_grad = tape.gradient(cost, [W, b])

        W.assign_sub(learning_rate * W_grad)
        b.assign_sub(learning_rate * b_grad)

    if i % 400 == 0:
        print('\t >>> Bstch: {:<3} Weights: [{:}, {:}] \n\t\t Bias: {:}, cost: {:} \n'.format(i, W.numpy()[0][0], W.numpy()[1][0], b.numpy(), cost.numpy()))        



	 >>> Bstch: 0   Weights: [-1.1069523096084595, 1.531254768371582] 
		 Bias: [0.3891292], cost: 5.080659866333008 

	 >>> Bstch: 400 Weights: [0.44699472188949585, 0.9109866619110107] 
		 Bias: [-2.3015914], cost: 2.2290866374969482 

	 >>> Bstch: 800 Weights: [1.0215262174606323, 1.1129134893417358] 
		 Bias: [-3.9197462], cost: 1.4660948514938354 

	 >>> Bstch: 1200 Weights: [1.3341188430786133, 1.3564225435256958] 
		 Bias: [-5.06228], cost: 1.0973552465438843 

	 >>> Bstch: 1600 Weights: [1.558021903038025, 1.564527988433838] 
		 Bias: [-5.9444833], cost: 0.8783029913902283 

	 >>> Bstch: 2000 Weights: [1.7369108200073242, 1.7390990257263184] 
		 Bias: [-6.663596], cost: 0.7328943014144897 



<font size = 2>***연이어 우리는 Softmax를 이해하기 위해, 먼저 Sigmoid 기반의 Multinomial classification을 정의하고, 해당 배경을 가지고 Softmax Regression을 이해해 볼 것입니다.***</font>

In [75]:
a = tf.constant([['WA1', 'WA2', 'WA3'],
             ['WB1', 'WB2', 'WB3'],
             ['WC1', 'WC2', 'WC3']])
b = tf.constant([['x1'],
                 ['x2'],
                 ['x3']])
c = tf.constant([['WA1x1 + WA2x2 + WA3x3'],
                 ['WB1x1 + WB2x2 + WB3x3'],
                 ['WC1x1 + WC2x2 + WC3x3']])

print('\n')
print('a: ', a)
print('\n')
print('b: ', b)
print('\n')
print('c: ', c)
print('\n')



a:  tf.Tensor(
[[b'WA1' b'WA2' b'WA3']
 [b'WB1' b'WB2' b'WB3']
 [b'WC1' b'WC2' b'WC3']], shape=(3, 3), dtype=string)


b:  tf.Tensor(
[[b'x1']
 [b'x2']
 [b'x3']], shape=(3, 1), dtype=string)


c:  tf.Tensor(
[[b'WA1x1 + WA2x2 + WA3x3']
 [b'WB1x1 + WB2x2 + WB3x3']
 [b'WC1x1 + WC2x2 + WC3x3']], shape=(3, 1), dtype=string)




<font size = 2>***Multinomial classification을 Sifgmoid를 통해 정의 하면 위에서 정의한 각 a, b, c에 대하여 a * b = c인 것과 같습니다. 각, $z = \sum_{i=1}^{3} (W_i*X_i)$는 hypothesis인 Sigmoid를 거쳐 $\bar{Y}$를 얻게 됩니다. 여기서 중요한 것은 각 $\bar{Y}$를 얻게 된다는 것입니다.***</font>


"A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes." (https://www.tensorflow.org/guide/tensor)

It should't surprise you that tensors are a fundemental apsect of TensorFlow. They are the main objects that are passed around and manipluated throughout the program. Each tensor represents a partialy defined computation that will eventually produce a value. TensorFlow programs work by building a graph of Tensor objects that details how tensors are related. Running different parts of the graph allow results to be generated.

Each tensor has a data type and a shape. 

**Data Types Include**: float32, int32, string and others.

**Shape**: Represents the dimension of data.

Just like vectors and matrices tensors can have operations applied to them like addition, subtraction, dot product, cross product etc.

In the next sections we will discuss some different properties of tensors. This is to make you more familiar with how tensorflow represnts data and how you can manipulate this data.
